/*
 * Copyright 2018 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NIS2 API Endpoints
 * This document defines all the nis2 api endpoints
 *
 * OpenAPI spec version: 0.9.1
 * Contact: guillem@nemeurope.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import FundsLockInfo from './FundsLockInfo';

/**
* The FundsLockInfoDTO model module.
* @module model/FundsLockInfoDTO
* @version 0.9.1
*/
export default class FundsLockInfoDTO {
    /**
    * Constructs a new <code>FundsLockInfoDTO</code>.
    * @alias module:model/FundsLockInfoDTO
    * @class
    * @param lock {module:model/FundsLockInfo} 
    */

    constructor(lock) {
        

        
        

        this['lock'] = lock;

        
    }

    /**
    * Constructs a <code>FundsLockInfoDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/FundsLockInfoDTO} obj Optional instance to populate.
    * @return {module:model/FundsLockInfoDTO} The populated <code>FundsLockInfoDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FundsLockInfoDTO();

            
            
            

            if (data.hasOwnProperty('lock')) {
                obj['lock'] = FundsLockInfo.constructFromObject(data['lock']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/FundsLockInfo} lock
    */
    lock = undefined;








}


