/**
 * NIS2 API Endpoints
 * This document defines all the nis2 api endpoints
 *
 * OpenAPI spec version: 0.9.1
 * Contact: guillem@nemeurope.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import LockFundsInfo from './LockFundsInfo';





/**
* The LockFundsInfoDTO model module.
* @module model/LockFundsInfoDTO
* @version 0.9.1
*/
export default class LockFundsInfoDTO {
    /**
    * Constructs a new <code>LockFundsInfoDTO</code>.
    * @alias module:model/LockFundsInfoDTO
    * @class
    * @param lock {module:model/LockFundsInfo} 
    */

    constructor(lock) {
        

        
        

        this['lock'] = lock;

        
    }

    /**
    * Constructs a <code>LockFundsInfoDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LockFundsInfoDTO} obj Optional instance to populate.
    * @return {module:model/LockFundsInfoDTO} The populated <code>LockFundsInfoDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LockFundsInfoDTO();

            
            
            

            if (data.hasOwnProperty('lock')) {
                obj['lock'] = LockFundsInfo.constructFromObject(data['lock']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/LockFundsInfo} lock
    */
    lock = undefined;








}


