/**
 * NIS2 API Endpoints
 * This document defines all the nis2 api endpoints
 *
 * OpenAPI spec version: 0.9.1
 * Contact: guillem@nemeurope.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import UInt64DTO from './UInt64DTO';





/**
* The LockFundsInfo model module.
* @module model/LockFundsInfo
* @version 0.9.1
*/
export default class LockFundsInfo {
    /**
    * Constructs a new <code>LockFundsInfo</code>.
    * @alias module:model/LockFundsInfo
    * @class
    * @param account {String} 
    * @param accountAddress {String} 
    * @param mosaicId {module:model/UInt64DTO} 
    * @param amount {module:model/UInt64DTO} 
    * @param height {module:model/UInt64DTO} 
    * @param status {Number} 
    * @param hash {String} 
    */

    constructor(account, accountAddress, mosaicId, amount, height, status, hash) {
        

        
        

        this['account'] = account;this['accountAddress'] = accountAddress;this['mosaicId'] = mosaicId;this['amount'] = amount;this['height'] = height;this['status'] = status;this['hash'] = hash;

        
    }

    /**
    * Constructs a <code>LockFundsInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LockFundsInfo} obj Optional instance to populate.
    * @return {module:model/LockFundsInfo} The populated <code>LockFundsInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LockFundsInfo();

            
            
            

            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'String');
            }
            if (data.hasOwnProperty('accountAddress')) {
                obj['accountAddress'] = ApiClient.convertToType(data['accountAddress'], 'String');
            }
            if (data.hasOwnProperty('mosaicId')) {
                obj['mosaicId'] = UInt64DTO.constructFromObject(data['mosaicId']);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = UInt64DTO.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = UInt64DTO.constructFromObject(data['height']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} account
    */
    account = undefined;
    /**
    * @member {String} accountAddress
    */
    accountAddress = undefined;
    /**
    * @member {module:model/UInt64DTO} mosaicId
    */
    mosaicId = undefined;
    /**
    * @member {module:model/UInt64DTO} amount
    */
    amount = undefined;
    /**
    * @member {module:model/UInt64DTO} height
    */
    height = undefined;
    /**
    * @member {Number} status
    */
    status = undefined;
    /**
    * @member {String} hash
    */
    hash = undefined;








}


