/*
 * Copyright 2018 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

 /**
 * NIS2 API Endpoints
 * This document defines all the nis2 api endpoints
 *
 * OpenAPI spec version: 0.9.0
 * Contact: guillem@nemeurope.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The MerkleTreeItemDTO model module.
* @module model/MerkleTreeItemDTO
* @version 0.9.0
*/
export default class MerkleTreeItemDTO {
    /**
    * Constructs a new <code>MerkleTreeItemDTO</code>.
    * @alias module:model/MerkleTreeItemDTO
    * @class
    * @param position {Number} 
    * @param hash {String} 
    */

    constructor(position, hash) {
        

        
        

        this['position'] = position;this['hash'] = hash;

        
    }

    /**
    * Constructs a <code>MerkleTreeItemDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MerkleTreeItemDTO} obj Optional instance to populate.
    * @return {module:model/MerkleTreeItemDTO} The populated <code>MerkleTreeItemDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerkleTreeItemDTO();

            
            
            

            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'Number');
            }
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} position
    */
    position = undefined;
    /**
    * @member {String} hash
    */
    hash = undefined;








}


