/*
 * Copyright 2018 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NIS2 API Endpoints
 * This document defines all the nis2 api endpoints
 *
 * OpenAPI spec version: 0.9.1
 * Contact: guillem@nemeurope.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import UInt64DTO from './UInt64DTO';





/**
* The SecretLockDTO model module.
* @module model/SecretLockDTO
* @version 0.9.1
*/
export default class SecretLockDTO {
    /**
    * Constructs a new <code>SecretLockDTO</code>.
    * @alias module:model/SecretLockDTO
    * @class
    * @param account {String} 
    * @param accountAddress {String} 
    * @param mosaicId {module:model/UInt64DTO} 
    * @param amount {module:model/UInt64DTO} 
    * @param height {module:model/UInt64DTO} 
    * @param status {Number} 
    * @param hashAlgorithm {Number} 
    * @param secret {String} 
    * @param recipient {String} 
    */

    constructor(account, accountAddress, mosaicId, amount, height, status, hashAlgorithm, secret, recipient) {
        

        
        

        this['account'] = account;this['accountAddress'] = accountAddress;this['mosaicId'] = mosaicId;this['amount'] = amount;this['height'] = height;this['status'] = status;this['hashAlgorithm'] = hashAlgorithm;this['secret'] = secret;this['recipient'] = recipient;

        
    }

    /**
    * Constructs a <code>SecretLockDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SecretLockDTO} obj Optional instance to populate.
    * @return {module:model/SecretLockDTO} The populated <code>SecretLockDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecretLockDTO();

            
            
            

            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'String');
            }
            if (data.hasOwnProperty('accountAddress')) {
                obj['accountAddress'] = ApiClient.convertToType(data['accountAddress'], 'String');
            }
            if (data.hasOwnProperty('mosaicId')) {
                obj['mosaicId'] = UInt64DTO.constructFromObject(data['mosaicId']);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = UInt64DTO.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = UInt64DTO.constructFromObject(data['height']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('hashAlgorithm')) {
                obj['hashAlgorithm'] = ApiClient.convertToType(data['hashAlgorithm'], 'Number');
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
            if (data.hasOwnProperty('recipient')) {
                obj['recipient'] = ApiClient.convertToType(data['recipient'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} account
    */
    account = undefined;
    /**
    * @member {String} accountAddress
    */
    accountAddress = undefined;
    /**
    * @member {module:model/UInt64DTO} mosaicId
    */
    mosaicId = undefined;
    /**
    * @member {module:model/UInt64DTO} amount
    */
    amount = undefined;
    /**
    * @member {module:model/UInt64DTO} height
    */
    height = undefined;
    /**
    * @member {Number} status
    */
    status = undefined;
    /**
    * @member {Number} hashAlgorithm
    */
    hashAlgorithm = undefined;
    /**
    * @member {String} secret
    */
    secret = undefined;
    /**
    * @member {String} recipient
    */
    recipient = undefined;








}


